### ISSUE TITLE
set: Symbol’s value as variable is void: js--treesit-sentence-nodes (Emacs 29.1)

### ISSUE THREAD

**Issue by MarkusPfundstein** [xhcoding/qml-ts-mode#1]
Hi, 

first of all, thanks a lot for this package! Very happy about it.

But I ran in some issue: I followed the install instructions, and I get this error in the minibuffer when activating qml-ts-mode

`set: Symbol’s value as variable is void: js--treesit-sentence-nodes`

Emacs version: GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version
3.24.38, cairo version 1.17.8)

The offending line is:
```
(setq-local treesit-sentence-type-regexp
             (regexp-opt js--treesit-sentence-nodes))
```
When I comment it out, qml-ts-mode starts correctly and I see nice syntax highlighting. However js highlighting is obviously broken :-)

Any idea?

**Comment by xhcoding** [comment]
Perhaps you need to update Emacs or add relevant definitions.


https://github.com/emacs-mirror/emacs/blob/76cf700ecb78cb465bcd05ae2b2fb0d28e4d0aed/lisp/progmodes/js.el#L3802

**Comment by dcunited001** [comment]
I too am running 29.1

```
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)"
```

I'm not sure why this line is not merged into the source tree used for my build (see [blame](
https://github.com/emacs-mirror/emacs/blame/5c43ef86bf169a79b87bd082d2f884757f7c2efc/lisp/progmodes/js.el#L3805-L3827))

Ensuring `js--treesit-sentence-nodes` has a value seems to work.

also, can you add a license to the project? it's required for building packages in guix

**Comment by xhcoding** [comment]
> also, can you add a license to the project? it's required for building packages in guix

DONE

**Comment by dcunited001** [comment]
thanks!

**Comment by fuzy112** [comment]
Hi @xhcoding 

I searched in the Emacs 29.2 source tree for `treesit-sentence-type-regexp` and `js--treesit-sentence-nodes` and didn't find them.

It seems that those definitions only exist in the master branch.

**Comment by smartmic** [comment]
Same here. I am using Emacs 29.3 on Void Linux as provided by package and it does not work out-of-the-box. Adding `(defvar js--treesit-sentence-nodes … )` in my init.el feels like a clumsy workaround.
